spring.datasource.url=jdbc:mysql://18.61.227.114:3306/notif_db
spring.datasource.username=${NOTIF_DB_USERNAME}
spring.datasource.password=${NOTIF_DB_PASSWORD}
spring.rabbitmq.host=18.61.227.114
logging.level.com.portfolio.notification=INFO
